from __future__ import annotations

# Application identity
APP_NAME = "project-optima"
APP_NAMESPACE = "rra"
APP_VERSION = "0.1.0"

# Logging
DEFAULT_LOGGER_NAME = "rra"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_TIMESTAMP_PRECISION = "milliseconds"
MAX_LOG_MESSAGE_LENGTH = 4096
MAX_EXCEPTION_TRACEBACK_FRAMES = 50

# Retry and backoff
DEFAULT_RETRY_ATTEMPTS = 5
DEFAULT_RETRY_BASE_DELAY_SECONDS = 0.25
DEFAULT_RETRY_MAX_DELAY_SECONDS = 8.0
DEFAULT_RETRY_BACKOFF_MULTIPLIER = 2.0
DEFAULT_RETRY_JITTER_SECONDS = 0.2
DEFAULT_RETRY_TIMEOUT_SECONDS = 30.0

# Rate limiting
DEFAULT_RATE_LIMIT_CAPACITY = 10
DEFAULT_RATE_LIMIT_REFILL_RATE = 5.0
DEFAULT_RATE_LIMIT_TIMEOUT_SECONDS = 2.0

# Circuit breaker
DEFAULT_CIRCUIT_BREAKER_FAILURE_THRESHOLD = 5
DEFAULT_CIRCUIT_BREAKER_RECOVERY_TIMEOUT_SECONDS = 30.0
DEFAULT_CIRCUIT_BREAKER_HALF_OPEN_MAX_CALLS = 1

# Subprocess and execution
DEFAULT_SUBPROCESS_TIMEOUT_SECONDS = 10.0
DEFAULT_SUBPROCESS_KILL_GRACE_SECONDS = 1.0
DEFAULT_COMMAND_RETRY_ATTEMPTS = 3

# Kraken CLI
DEFAULT_KRAKEN_CLI_BINARY = "kraken"
DEFAULT_KRAKEN_CLI_OUTPUT_FORMAT = "json"
DEFAULT_KRAKEN_CLI_TIMEOUT_SECONDS = 3.0
DEFAULT_KRAKEN_CLI_WARM_PATH_TIMEOUT_SECONDS = 1.0
DEFAULT_KRAKEN_MARKET_DATA_TIMEOUT_SECONDS = 1.5
DEFAULT_KRAKEN_ORDER_TIMEOUT_SECONDS = 2.0

# Groq / inference
DEFAULT_GROQ_REQUEST_TIMEOUT_SECONDS = 5.0
DEFAULT_GROQ_MAX_RETRIES = 3
DEFAULT_GROQ_TEMPERATURE = 0.0
DEFAULT_GROQ_MAX_TOKENS = 1024

# LangGraph / persistence
DEFAULT_THREAD_ID_PREFIX = "rra-thread"
DEFAULT_CHECKPOINT_NAMESPACE = "rra-checkpoints"
DEFAULT_CHECKPOINT_FLUSH_INTERVAL_SECONDS = 1.0
DEFAULT_STATE_VERSION = 1

# ERC-8004 / trust layer
DEFAULT_ERC8004_CHAIN_ID = 8453
DEFAULT_TRUST_SCORE_FLOOR = 0.6
DEFAULT_ATTESTATION_TTL_SECONDS = 300
DEFAULT_REGISTRY_CACHE_TTL_SECONDS = 60

# Market data and strategy
DEFAULT_MARKET_SNAPSHOT_TTL_SECONDS = 1.0
DEFAULT_SENTIMENT_WINDOW_SECONDS = 30
DEFAULT_REGIME_REEVALUATION_INTERVAL_SECONDS = 5.0
DEFAULT_SIGNAL_SCORE_FLOOR = 0.55
DEFAULT_POSITION_SIZE_BPS = 100
DEFAULT_MAX_POSITION_SIZE_BPS = 500
DEFAULT_RISK_CHECK_TIMEOUT_SECONDS = 1.0

# HTTP and network defaults
DEFAULT_HTTP_CONNECT_TIMEOUT_SECONDS = 3.0
DEFAULT_HTTP_READ_TIMEOUT_SECONDS = 5.0
DEFAULT_HTTP_WRITE_TIMEOUT_SECONDS = 5.0
DEFAULT_HTTP_POOL_TIMEOUT_SECONDS = 5.0

# Serialization and payload guards
DEFAULT_JSON_INDENT = 2
MAX_JSON_PAYLOAD_BYTES = 1_048_576
MAX_NDJSON_LINE_BYTES = 262_144

# Time conversions
MILLISECONDS_PER_SECOND = 1_000
MICROSECONDS_PER_SECOND = 1_000_000
NANOSECONDS_PER_SECOND = 1_000_000_000

# Common environment variable names
ENV_LOG_LEVEL = "RRA_LOG_LEVEL"
ENV_GROQ_API_KEY = "GROQ_API_KEY"
ENV_KRAKEN_CLI_PATH = "KRAKEN_CLI_PATH"
ENV_KRAKEN_PROFILE = "KRAKEN_PROFILE"
ENV_LANGGRAPH_CHECKPOINT_DB = "LANGGRAPH_CHECKPOINT_DB"
ENV_ERC8004_RPC_URL = "ERC8004_RPC_URL"
ENV_ERC8004_REGISTRY_ADDRESS = "ERC8004_REGISTRY_ADDRESS"
